---

apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
type: Opaque
data:
  JICOFO_COMPONENT_SECRET: example-password
  JVB_AUTH_PASSWORD: example-password
  JICOFO_AUTH_PASSWORD: example-password
