---

apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
type: Opaque
data:
  JICOFO_COMPONENT_SECRET: ZXhhbXBsZS1wYXNzd29yZAo=
  JVB_AUTH_PASSWORD: ZXhhbXBsZS1wYXNzd29yZAo=
  JICOFO_AUTH_PASSWORD: ZXhhbXBsZS1wYXNzd29yZAo=
