---

apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
type: Opaque
data:
  JICOFO_COMPONENT_SECRET: ZXhhbXBsZS1wYXNzd29yZA==
  JVB_AUTH_PASSWORD: ZXhhbXBsZS1wYXNzd29yZA==
  JICOFO_AUTH_PASSWORD: ZXhhbXBsZS1wYXNzd29yZA==
